### ISSUE TITLE
Unable to find user botman

### ISSUE THREAD

**Issue by absentbird** [dglib/bots-edi#1]
When attempting to run the docker image I get this error:

```
docker: Error response from daemon: unable to find user botman: no matching entries in passwd file.
ERRO[0000] error waiting for container: context canceled
```

I think it's because the Dockerfile has `USER botman` but doesn't create the user.
It should be resolved by adding a line like this before the `USER` line:

```
RUN useradd -ms /bin/bash botman
```

**Comment by shakerg** [comment]
Good catch, I've removed the user switch to 'botman' and 'root', there isn't any need to use it.
